### ISSUE TITLE
Compile error with Android SDK V29

### ISSUE THREAD

**Issue by mtbsteve** [nathanRamaNoodles/Tinker-Controller#5]
Thanks for this great project!
When I set the target and compile SDK version to 29 (Android 10.0 Q) in the `build.graddle` file the compiler fails with:
```
> org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':libraries:Cyanea:compileDebugKotlin'.
> 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
```
Up to SDK version 28 everything is fine. I am on Android Studio 3.5.3 on Ubuntu. SDK V29 is installed. What can I do to support the latest devices?

**Comment by nathanRamaNoodles** [comment]
It looks like the Cyanea theme engine is fighting the update.  You may have to go over to [Cyanea](https://github.com/jaredrummler/Cyanea) and use the latest Cynea Library.

Simply delete the Cynea content's in my app, and import the new one from the link above.  Though, it might not work since Jared didn't update to AndroidQ either.  Android's Gradle dependency is a hell to deal with.

**Comment by mtbsteve** [comment]
Thanks- I updated to version 1.0.2 and now it works fine on Android 10.
